### ISSUE TITLE
1- format your eslint config file

### ISSUE THREAD

**Issue by artmarydotir** [SaraPrz/js-info-tasks#1]
![Screenshot from 2023-07-09 12-12-47](https://github.com/SaraPrz/js-info-tasks/assets/11363931/05cfc074-8c63-450c-b498-f034fa40ceab)

convert to:

![Screenshot from 2023-07-09 12-17-52](https://github.com/SaraPrz/js-info-tasks/assets/11363931/beba8b75-bd75-4206-b27a-8c5ea8b154a1)

**Comment by SaraPrz** [comment]
formatted it with prettier

**Comment by SaraPrz** [comment]
formatted it with prettier
